################################################################################
# Judge0 Configuration — for internal use only
################################################################################

# ----------------------- Server -----------------------
JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
ENABLE_SUBMISSION_DELETE=true
ENABLE_BATCHED_SUBMISSIONS=true
MAX_SUBMISSION_BATCH_SIZE=20
ENABLE_CALLBACKS=true
ENABLE_ADDITIONAL_FILES=true

# ----------------------- Workers -----------------------
INTERVAL=0.1
COUNT=2
MAX_QUEUE_SIZE=100

# ----------------------- Redis -----------------------
REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0redispassword

# ----------------------- PostgreSQL -----------------------
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0password

# ----------------------- Rails -----------------------
RAILS_ENV=production
RAILS_MAX_THREADS=5
RAILS_SERVER_PROCESSES=2

# ----------------------- Submission Defaults -----------------------
CPU_TIME_LIMIT=5
CPU_EXTRA_TIME=1
WALL_TIME_LIMIT=10
MEMORY_LIMIT=128000
STACK_LIMIT=64000
MAX_PROCESSES_AND_OR_THREADS=60
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false
MAX_FILE_SIZE=1024
NUMBER_OF_RUNS=1
REDIRECT_STDERR_TO_STDOUT=false
ENABLE_NETWORK=false
