services:
  api:
    build: ../..
    container_name: go-api
    command: ["./server"]
    env_file: ../../.env
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=api
      
  worker:
    build: ../..
    container_name: go-worker
    command: ["./worker"]
    env_file: ../../.env
    environment:
      - SERVICE_NAME=worker

networks:
  default:
    name: app-network
    external: true
      